### ISSUE TITLE
uhh

### ISSUE THREAD

**Issue by DaDevGuy** [itschasa/luxury#1]
i actually paid for a claim and didnt get lmao

**Comment by itschasa** [comment]
The owner, Dylan (Luxury), left with no ability to contact him. He took all payments. I was just a developer for him. I do not have your money or the ability to refund you. Sorry :/

**Comment by LuxuryBoosts** [comment]
> i actually paid for a claim and didnt get lmao

Might start again, if you did have a order backup of db was made so it will be there
